name: NUOPC Component Testing Action
author: Ufuk Turuncoglu (ESMF/CGD/NCAR)
description: Tests given earth system model component in a isolated way forced by data component
inputs:
  architecture:
    description: spack target architecture
    required: false
    default: x86_64_v4
  dependencies:
    description: list of packages to install
    required: true
  dependencies_install_dir:
    description: spack dependency installation directory 
    required: false
    default: ~/.spack-ci

runs:
  using: "composite"
  steps:
    # checkout base repository
    - name: Checkout Component Repository
      uses: actions/checkout@v3

    # prepare core environment
    - name: Install Core Development Tools
      run: |
        sudo apt-get update
        sudo apt-get install tar unzip file gringo
        sudo apt-get install build-essential binutils-dev gfortran
        sudo apt-get install python3-dev python3-boto3 python3-yaml
        sudo apt-get install wget awscli ca-certificates gh
      shell: bash

    # concretize dependencies
    - name: Concretize Spack Environment Using YAML Specification
      id: concretize-deps
      run: |
        $GITHUB_ACTION_PATH/scripts/concretize_deps.sh \
          -a ${{ inputs.architecture }} \
          -d $(echo "${{ inputs.dependencies }}" | awk '$1=$1' RS= OFS=,) \
          -i ${{ inputs.dependencies_install_dir }} \
          -r $GITHUB_WORKSPACE
      shell: bash

    # restore dependencies from cache
    - name: Restore Dependencies
      id: restore-deps 
      uses: actions/cache@v3
      with:
        path: ${{ inputs.dependencies_install_dir }} 
        key: spack-${{ runner.os }}-${{ inputs.architecture }}-${{ hashFiles('**/spack.lock') }}
        restore-keys: |
          spack-${{ runner.os }}-${{ inputs.architecture }}-${{ hashFiles('**/spack.lock') }}

    # install dependencies
    - name: Install Dependencies with Spack 
      id: install-deps
      run: |
        $GITHUB_ACTION_PATH/scripts/install_deps.sh \
          -r $GITHUB_WORKSPACE
      shell: bash

    # checkout data models
    - name: Checkout CDEPS
      uses: actions/checkout@v3
      with:
        repository: uturuncoglu/CDEPS
        path: ${{ github.workspace }}/cdeps
        ref: hotfix/std_build

    # build and install data models
    - name: Build and Install CDEPS
      run: |
        export PATH=${{ github.workspace }}/../.spack-ci/view/bin:$PATH
        export ESMFMKFILE=${{ github.workspace }}/../.spack-ci/view/lib/esmf.mk
        export FC=gfortran
        cd ${{ github.workspace }}/cdeps
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} \
          -DPIO_C_LIBRARY=${{ github.workspace }}/../.spack-ci/view/lib \
          -DPIO_C_INCLUDE_DIR=${{ github.workspace }}/../.spack-ci/view/include \
          -DPIO_Fortran_LIBRARY=${{ github.workspace }}/../.spack-ci/view/lib \
          -DPIO_Fortran_INCLUDE_DIR=${{ github.workspace }}/../.spack-ci/view/include \
          -DCMAKE_Fortran_FLAGS="-ffree-line-length-none -fallow-argument-mismatch -fallow-invalid-boz" \
          -DDISABLE_FoX=ON ../
        make
        make install
      shell: bash
